Traceback (most recent call last):
  File "/home/sara/Documents/GitHub/Pipeline/main.py", line 23, in <module>
    downloader = UniversiticeDownloader()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/Documents/GitHub/Pipeline/downloader.py", line 21, in __init__
    self.driver = self._configure_driver()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/Documents/GitHub/Pipeline/downloader.py", line 36, in _configure_driver
    return webdriver.Chrome(
           ^^^^^^^^^^^^^^^^^
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    super().__init__(
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 257, in __init__
    self.start_session(capabilities)
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir
Stacktrace:
#0 0x6203c44ac7fa <unknown>
#1 0x6203c3f50e90 <unknown>
#2 0x6203c3f8acfb <unknown>
#3 0x6203c3f86a3f <unknown>
#4 0x6203c3fd6c15 <unknown>
#5 0x6203c3fd6136 <unknown>
#6 0x6203c3fc8013 <unknown>
#7 0x6203c3f94b3b <unknown>
#8 0x6203c3f957a1 <unknown>
#9 0x6203c4471b9b <unknown>
#10 0x6203c4475a8a <unknown>
#11 0x6203c4459912 <unknown>
#12 0x6203c4476604 <unknown>
#13 0x6203c443e74f <unknown>
#14 0x6203c449a678 <unknown>
#15 0x6203c449a856 <unknown>
#16 0x6203c44ab666 <unknown>
#17 0x741ec8494ac3 <unknown>

fichier ZIP téléchargé : /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786.zip
Extraction reussie dans /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786
fichier ZIP téléchargé : /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786.zip
Extraction reussie dans /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786
fichier ZIP téléchargé : /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786.zip
Extraction reussie dans /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786
Traceback (most recent call last):
  File "/home/sara/Documents/GitHub/Pipeline/main.py", line 25, in <module>
    downloader.login()
  File "/home/sara/Documents/GitHub/Pipeline/downloader.py", line 41, in login
    self.driver.get("https://universitice.univ-rouen.fr/")
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 472, in get
    self.execute(Command.GET, {"url": url})
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x6407516657fa <unknown>
#1 0x640751109e90 <unknown>
#2 0x640751100f67 <unknown>
#3 0x6407510f2039 <unknown>
#4 0x6407510f3d3d <unknown>
#5 0x6407510f23ce <unknown>
#6 0x6407510f1d6e <unknown>
#7 0x6407510f1a1f <unknown>
#8 0x6407510ef89f <unknown>
#9 0x6407510f005a <unknown>
#10 0x64075110d3c9 <unknown>
#11 0x6407511a7cc5 <unknown>
#12 0x640751181242 <unknown>
#13 0x6407511a7135 <unknown>
#14 0x640751181013 <unknown>
#15 0x64075114db3b <unknown>
#16 0x64075114e7a1 <unknown>
#17 0x64075162ab9b <unknown>
#18 0x64075162ea8a <unknown>
#19 0x640751612912 <unknown>
#20 0x64075162f604 <unknown>
#21 0x6407515f774f <unknown>
#22 0x640751653678 <unknown>
#23 0x640751653856 <unknown>
#24 0x640751664666 <unknown>
#25 0x7a2a48a94ac3 <unknown>

Traceback (most recent call last):
  File "/home/sara/Documents/GitHub/Pipeline/main.py", line 25, in <module>
    downloader.login()
  File "/home/sara/Documents/GitHub/Pipeline/downloader.py", line 41, in login
    self.driver.get("https://universitice.univ-rouen.fr/")
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 472, in get
    self.execute(Command.GET, {"url": url})
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x5e28f91a37fa <unknown>
#1 0x5e28f8c47e90 <unknown>
#2 0x5e28f8c3ef67 <unknown>
#3 0x5e28f8c30039 <unknown>
#4 0x5e28f8c31d3d <unknown>
#5 0x5e28f8c303ce <unknown>
#6 0x5e28f8c2fd6e <unknown>
#7 0x5e28f8c2fa1f <unknown>
#8 0x5e28f8c2d89f <unknown>
#9 0x5e28f8c2e05a <unknown>
#10 0x5e28f8c4b3c9 <unknown>
#11 0x5e28f8ce5cc5 <unknown>
#12 0x5e28f8cbf242 <unknown>
#13 0x5e28f8ce5135 <unknown>
#14 0x5e28f8cbf013 <unknown>
#15 0x5e28f8c8bb3b <unknown>
#16 0x5e28f8c8c7a1 <unknown>
#17 0x5e28f9168b9b <unknown>
#18 0x5e28f916ca8a <unknown>
#19 0x5e28f9150912 <unknown>
#20 0x5e28f916d604 <unknown>
#21 0x5e28f913574f <unknown>
#22 0x5e28f9191678 <unknown>
#23 0x5e28f9191856 <unknown>
#24 0x5e28f91a2666 <unknown>
#25 0x7c3e83894ac3 <unknown>

Traceback (most recent call last):
  File "/home/sara/Documents/GitHub/Pipeline/main.py", line 25, in <module>
    downloader.login()
  File "/home/sara/Documents/GitHub/Pipeline/downloader.py", line 41, in login
    self.driver.get("https://universitice.univ-rouen.fr/")
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 472, in get
    self.execute(Command.GET, {"url": url})
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x64b4241507fa <unknown>
#1 0x64b423bf4e90 <unknown>
#2 0x64b423bebf67 <unknown>
#3 0x64b423bdd039 <unknown>
#4 0x64b423bded3d <unknown>
#5 0x64b423bdd3ce <unknown>
#6 0x64b423bdcd6e <unknown>
#7 0x64b423bdca1f <unknown>
#8 0x64b423bda89f <unknown>
#9 0x64b423bdb05a <unknown>
#10 0x64b423bf83c9 <unknown>
#11 0x64b423c92cc5 <unknown>
#12 0x64b423c6c242 <unknown>
#13 0x64b423c92135 <unknown>
#14 0x64b423c6c013 <unknown>
#15 0x64b423c38b3b <unknown>
#16 0x64b423c397a1 <unknown>
#17 0x64b424115b9b <unknown>
#18 0x64b424119a8a <unknown>
#19 0x64b4240fd912 <unknown>
#20 0x64b42411a604 <unknown>
#21 0x64b4240e274f <unknown>
#22 0x64b42413e678 <unknown>
#23 0x64b42413e856 <unknown>
#24 0x64b42414f666 <unknown>
#25 0x7f6940494ac3 <unknown>

Traceback (most recent call last):
  File "/home/sara/Documents/GitHub/Pipeline/main.py", line 25, in <module>
    downloader.login()
  File "/home/sara/Documents/GitHub/Pipeline/downloader.py", line 41, in login
    self.driver.get("https://universitice.univ-rouen.fr/")
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 472, in get
    self.execute(Command.GET, {"url": url})
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x5a5f843c97fa <unknown>
#1 0x5a5f83e6de90 <unknown>
#2 0x5a5f83e64f67 <unknown>
#3 0x5a5f83e56039 <unknown>
#4 0x5a5f83e57d3d <unknown>
#5 0x5a5f83e563ce <unknown>
#6 0x5a5f83e55d6e <unknown>
#7 0x5a5f83e55a1f <unknown>
#8 0x5a5f83e5389f <unknown>
#9 0x5a5f83e5405a <unknown>
#10 0x5a5f83e713c9 <unknown>
#11 0x5a5f83f0bcc5 <unknown>
#12 0x5a5f83ee5242 <unknown>
#13 0x5a5f83f0b135 <unknown>
#14 0x5a5f83ee5013 <unknown>
#15 0x5a5f83eb1b3b <unknown>
#16 0x5a5f83eb27a1 <unknown>
#17 0x5a5f8438eb9b <unknown>
#18 0x5a5f84392a8a <unknown>
#19 0x5a5f84376912 <unknown>
#20 0x5a5f84393604 <unknown>
#21 0x5a5f8435b74f <unknown>
#22 0x5a5f843b7678 <unknown>
#23 0x5a5f843b7856 <unknown>
#24 0x5a5f843c8666 <unknown>
#25 0x726e2be94ac3 <unknown>

Traceback (most recent call last):
  File "/home/sara/Documents/GitHub/Pipeline/main.py", line 25, in <module>
    downloader.login()
  File "/home/sara/Documents/GitHub/Pipeline/downloader.py", line 41, in login
    self.driver.get("https://universitice.univ-rouen.fr/")
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 472, in get
    self.execute(Command.GET, {"url": url})
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55dcd90ee7fa <unknown>
#1 0x55dcd8b92e90 <unknown>
#2 0x55dcd8b89f67 <unknown>
#3 0x55dcd8b7b039 <unknown>
#4 0x55dcd8b7cd3d <unknown>
#5 0x55dcd8b7b3ce <unknown>
#6 0x55dcd8b7ad6e <unknown>
#7 0x55dcd8b7aa1f <unknown>
#8 0x55dcd8b7889f <unknown>
#9 0x55dcd8b7905a <unknown>
#10 0x55dcd8b963c9 <unknown>
#11 0x55dcd8c30cc5 <unknown>
#12 0x55dcd8c0a242 <unknown>
#13 0x55dcd8c30135 <unknown>
#14 0x55dcd8c0a013 <unknown>
#15 0x55dcd8bd6b3b <unknown>
#16 0x55dcd8bd77a1 <unknown>
#17 0x55dcd90b3b9b <unknown>
#18 0x55dcd90b7a8a <unknown>
#19 0x55dcd909b912 <unknown>
#20 0x55dcd90b8604 <unknown>
#21 0x55dcd908074f <unknown>
#22 0x55dcd90dc678 <unknown>
#23 0x55dcd90dc856 <unknown>
#24 0x55dcd90ed666 <unknown>
#25 0x7244a7094ac3 <unknown>

Traceback (most recent call last):
  File "/home/sara/Documents/GitHub/Pipeline/main.py", line 25, in <module>
    downloader.login()
  File "/home/sara/Documents/GitHub/Pipeline/downloader.py", line 41, in login
    self.driver.get("https://universitice.univ-rouen.fr/")
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 472, in get
    self.execute(Command.GET, {"url": url})
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x5d9813a5c7fa <unknown>
#1 0x5d9813500e90 <unknown>
#2 0x5d98134f7f67 <unknown>
#3 0x5d98134e9039 <unknown>
#4 0x5d98134ead3d <unknown>
#5 0x5d98134e93ce <unknown>
#6 0x5d98134e8d6e <unknown>
#7 0x5d98134e8a1f <unknown>
#8 0x5d98134e689f <unknown>
#9 0x5d98134e705a <unknown>
#10 0x5d98135043c9 <unknown>
#11 0x5d981359ecc5 <unknown>
#12 0x5d9813578242 <unknown>
#13 0x5d981359e135 <unknown>
#14 0x5d9813578013 <unknown>
#15 0x5d9813544b3b <unknown>
#16 0x5d98135457a1 <unknown>
#17 0x5d9813a21b9b <unknown>
#18 0x5d9813a25a8a <unknown>
#19 0x5d9813a09912 <unknown>
#20 0x5d9813a26604 <unknown>
#21 0x5d98139ee74f <unknown>
#22 0x5d9813a4a678 <unknown>
#23 0x5d9813a4a856 <unknown>
#24 0x5d9813a5b666 <unknown>
#25 0x796c14894ac3 <unknown>

Traceback (most recent call last):
  File "/home/sara/Documents/GitHub/Pipeline/main.py", line 25, in <module>
    downloader.login()
  File "/home/sara/Documents/GitHub/Pipeline/downloader.py", line 41, in login
    self.driver.get("https://universitice.univ-rouen.fr/")
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 472, in get
    self.execute(Command.GET, {"url": url})
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
  File "/home/sara/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x6285c93467fa <unknown>
#1 0x6285c8deae90 <unknown>
#2 0x6285c8de1f67 <unknown>
#3 0x6285c8dd3039 <unknown>
#4 0x6285c8dd4d3d <unknown>
#5 0x6285c8dd33ce <unknown>
#6 0x6285c8dd2d6e <unknown>
#7 0x6285c8dd2a1f <unknown>
#8 0x6285c8dd089f <unknown>
#9 0x6285c8dd105a <unknown>
#10 0x6285c8dee3c9 <unknown>
#11 0x6285c8e88cc5 <unknown>
#12 0x6285c8e62242 <unknown>
#13 0x6285c8e88135 <unknown>
#14 0x6285c8e62013 <unknown>
#15 0x6285c8e2eb3b <unknown>
#16 0x6285c8e2f7a1 <unknown>
#17 0x6285c930bb9b <unknown>
#18 0x6285c930fa8a <unknown>
#19 0x6285c92f3912 <unknown>
#20 0x6285c9310604 <unknown>
#21 0x6285c92d874f <unknown>
#22 0x6285c9334678 <unknown>
#23 0x6285c9334856 <unknown>
#24 0x6285c9345666 <unknown>
#25 0x7436df894ac3 <unknown>

fichier ZIP téléchargé : /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786.zip
Extraction reussie dans /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786
fichier ZIP téléchargé : /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786.zip
Extraction reussie dans /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786
fichier ZIP téléchargé : /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786.zip
Extraction reussie dans /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786
fichier ZIP téléchargé : /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786.zip
Extraction reussie dans /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786
fichier ZIP téléchargé : /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786.zip
Extraction reussie dans /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786
fichier ZIP téléchargé : /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786.zip
Extraction reussie dans /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786
fichier ZIP téléchargé : /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786.zip
Extraction reussie dans /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786
fichier ZIP téléchargé : /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786.zip
Extraction reussie dans /home/sara/Documents/GitHub/Pipeline/BAS-Dépots fichier .csv-1167786
